### ISSUE TITLE
能否增加 https://ip.skk.moe/ 的多出口的返回结果呢？

### ISSUE THREAD

**Issue by taotieren** [crystal-china/myip#2]
https://ip.skk.moe/ 返回国内和国外的 IP 来源，更适合国内环境使用。

**Comment by taotieren** [comment]
晚点用的试试看，好用的话晚点添加到 AUR 仓库里面

**Comment by zw963** [comment]
> https://ip.skk.moe/ 返回国内和国外的 IP 来源，更适合国内环境使用。

好的, 原来的正好有些失效了, 例如: ip138, 把我的 ip 都给 ban 了呢, 我试着增加看看.

**Comment by zw963** [comment]
这个项目主要问题是, 我没有用 headless 浏览器方案, 主要是考虑到 firefox/chrome 额外的需要安装 headless 包的这个步骤, 对于像获取 ip 这样一个小工具, 依赖太多了, 而且本质上, 我也是希望获取不依赖于浏览器配置的 IP 结果.

但这带来一个问题, 当访问你说的 "https://ip.skk.moe" 这样的网站时, 请求成功后, 他会立即返回, 返回的结果是 `获取中...`,  而不是期望的 IP 结果.

我刚刚像社区提问, 看看有没有解决办法, 再等等, 找不到解决办法的话, 我考虑就用 translater 一样的方案好了.

**Comment by zw963** [comment]
刚刚更新了两个版本, 最新 [0.4.8](https://github.com/crystal-china/myip/releases/tag/v0.4.8), 你可以试一下, README.md 里面有最新的截图效果, 支持完整的 ip.skk.moe 就不考虑了, 毕竟引入浏览器就引入了复杂性, portable 也不好,  目前实现, 甚至在 Windows  下也可以用的.

如果有那个 ip.skk.moe 里面某个特别的功能觉得有用, 可以新建一个 issue 单独提出来.

**Comment by taotieren** [comment]
已经添加到 AUR 和自建源了
还有一个需要注意的是
国内运营商现在开始回收公网 IPv4（包括动态公网 IPv4）
默认下发 公网 IPv6（包括动态公网 IPv6）
现在用户默认得到的内网 IPv4 和动态公网 IPv6
如果能反馈内网或公网 IPv4 和内网或公网 IPv6 的测试返回结果

**Comment by zw963** [comment]
> 国内运营商现在开始回收公网 IPv4（包括动态公网 IPv4）
> 默认下发 公网 IPv6（包括动态公网 IPv6）

我说呢, 最近返回的老是 IPv6, 为了获取 IPv4, 以及 ipv6 的详细地域信息, 新增了一些处理.
